### ISSUE TITLE
Library : Sort by date

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1485]
Sort by date must toggle between ascending and descending sorting . when clicked multiple times

**Comment by nvrqt03** [comment]
Currently no date in views with [ORDER BY DATE] button. (Issue 1414)

**Comment by leomaxi** [comment]
Explain

**Comment by nvrqt03** [comment]
We are wanting to sort by date, but there is no date to sort by.

![library order by date](https://user-images.githubusercontent.com/22177989/72155271-5dbd4a80-3378-11ea-9a20-2127a6767936.png)


There is an issue to put in the date, does this need to be done first in order to complete the sort by date?

![1414](https://user-images.githubusercontent.com/22177989/72155413-b2f95c00-3378-11ea-82c3-1c79d174faa2.png)

**Comment by nvrqt03** [comment]
I think I know what you're talking about - there's already an "uploadDate" available to sort by. I will try to figure this out.
