### ISSUE TITLE
Resources created on tablet shows up in library  

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1864]
Resources created on the tablet shows up in the library; on a tablet, we need to prompt them that the resource they are adding will be shared to the public library. To differential adding resource for myPersonals and adding resource for public  consumption 
<img width="978" alt="Screenshot 2020-06-19 at 5 10 01 PM" src="https://user-images.githubusercontent.com/2836302/85161708-b8c06b00-b24f-11ea-9462-b77bbf69776c.png">

**Comment by rrijal53** [comment]
It is working fine , we need to add resource from myPersonal page . Otherwise it will go to normal library
<img width="1440" alt="Screen Shot 2020-06-20 at 20 51 22" src="https://user-images.githubusercontent.com/9145217/85204963-de28a400-b337-11ea-8815-6ed2af6b5a8a.png">

<img width="355" alt="Screen Shot 2020-06-20 at 20 51 26" src="https://user-images.githubusercontent.com/9145217/85204960-d9fc8680-b337-11ea-8095-1ae47fc56fd0.png">
