### ISSUE TITLE
Task detail popup

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#1988]
Button on popup of task says Finish when it does not mark it as complete and just close popup which is confusing. We should say it as close

**Comment by leomaxi** [comment]
@lmmrssa :- Took me some time to figure out what the issue is about. Please add screenshots to make it easy to reproduce issues / more explanation will be best. 
<img width="1278" alt="Screenshot 2020-07-14 at 9 31 42 AM" src="https://user-images.githubusercontent.com/2836302/87409740-e8476680-c5b4-11ea-9f5c-771f8b064dbe.png">
